#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

NAME=timesanitycheck
SCRIPTNAME=/etc/init.d/$NAME
DIR=/var/run/$NAME
PIDFILE=$DIR/pid
FAIL_FILE=$DIR/fail
SUCCESS_FILE=$DIR/success
LOG=/var/log/$NAME.log

# Source configuration
if [ -e /etc/default/$NAME ]; then
   . /etc/default/$NAME
else
   echo "timesanitycheck: /etc/default/$NAME does not exist, using default.
   ## Expiration date in unixtime.
   ## date --date "17 MAY 2033 10:00:00" "+%s"
   ## 1999936800
   "
   EXPIRATION_UNIXTIME="1999936800"

   ## Convert seconds since the epoch (1970-01-01 UTC) (unixtime) to a date
   ## date --date="@1999936800"
fi

log() {
   echo "$@" >> "${LOG}"
}
