#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -e

source /usr/share/timesanitycheck/shared

time_sanity_check

echo "$time_sanity_check_msg_dynamic"

exit $time_sanity_check_exit_code
